// Elevate BSI — client data.
// This is the only file you need to edit to update the dashboard.
// Source: Notion "To-Do" board + client pages (last synced Sept 20, 2026).
//
// status:   "urgent" | "active" | "waiting" | "done" | "parked"
// type:     "retainer" (monthly) | "project" (one-time) | "internal"
// tasks:    [text, done, flag]   flag: "urgent" | "blocked" | undefined
// owed:     [[month, amount], ...]  unpaid invoices; remove a row once paid

window.ELEVATE_DATA = {
  asOf: "2026-09-20",

  clients: [
    {
      id: "relevate",
      name: "Relevate Solutions",
      contact: "Raymond Castro (Pastor Raymond)",
      color: "blue",
      emoji: "🔵",
      type: "retainer",
      value: 444,
      valueLabel: "$444 / mo",
      status: "urgent",
      services: ["Website", "Social", "Email / CRM", "SEO · GEO · AIO"],
      summary:
        "Accounting, tax, payroll and coaching for churches and small businesses. Hudson Valley NY, bilingual EN/ES.",
      next: "Schedule the Sept 20 batch through Oct 23 (29-day platform cap)",
      blockers: [
        "cPanel access (needed for llms.txt upload)",
        "Google Business Profile + Bing access",
        "Staff photos",
        "Mailchimp account",
      ],
      notion: "https://app.notion.com/p/39598dba651b81fcad10e8c7e524c0fa",
      tasks: [
        ["Outreach list compiled", true],
        ["Sept 20 production batch (statics, carousels, emails)", true],
        ["Schedule Sept 20 batch through Oct 23", false, "urgent"],
        ["Write + hand Pastor Raymond 4 reel scripts", false, "urgent"],
        ["Configure Mailchimp (templates + audience)", false],
        ["Northeast Market Expansion: hashtags + copy", false],
        ["Week of Oct 19: book Oct 24–31", false],
        ["Update Bing Search", false],
        ["Upload LLMs file into cPanel", false, "blocked"],
      ],
    },
    {
      id: "nyti",
      name: "NYTI",
      contact: "Pastor Raymond",
      color: "purple",
      emoji: "🎓",
      type: "project",
      value: 400,
      valueLabel: "$400 flat · paid",
      status: "urgent",
      services: ["12 statics", "4 AI reels", "Skool", "Facebook · ES"],
      summary:
        "Enrollment campaign. Launched Mon Sept 14. Spanish (usted), Facebook only.",
      next: "Record the final 4 reels, then edit + schedule. This closes the proposal.",
      blockers: [],
      notion: "https://app.notion.com/p/39898dba651b812e9e95cee34f181655",
      tasks: [
        ["12 statics created + scheduled", true],
        ["Skool community built", true],
        ["Skool community handed off", true],
        ["Handoff meeting with Pastor Ray", true],
        ["On-site Skool setup with students (Sept 14)", true],
        ["Record final 4 reels (was due Mon Sept 21)", false, "urgent"],
      ],
    },
    {
      id: "musica",
      name: "Escuela de Música",
      contact: "Pastor Raymond · Misión Internacional",
      color: "purple",
      emoji: "🎵",
      type: "project",
      value: 400,
      valueLabel: "$400 flat · paid",
      status: "urgent",
      services: ["12 statics", "4 reels", "Facebook · ES"],
      summary: "Enrollment campaign. Enrolling since Aug 18.",
      next: "Finalize + schedule reels 2–4",
      blockers: [],
      notion: "https://app.notion.com/p/39898dba651b812e9e95cee34f181655",
      tasks: [
        ["12 statics created + scheduled", true],
        ["4 reels shot (Sept 8)", true],
        ["Reel 1 of 4 finalized", true],
        ["Finalize + schedule reels 2–4", false, "urgent"],
      ],
    },
    {
      id: "warriors",
      name: "The Warriors Project",
      contact: "Robert",
      color: "orange",
      emoji: "🛡️",
      type: "retainer",
      value: 444,
      valueLabel: "$444 / mo",
      owed: [
        ["August 2026", 444],
        ["September 2026", 444],
      ],
      status: "urgent",
      services: ["Skool", "Workbook", "Social content"],
      summary:
        "12-module WARRIORS workbook + Skool community. Launched Sept 13. Free tier feeds a paid masterclass and 1:1 coaching.",
      next: "Start the next content cycle Mon Oct 5 (current batch runs through Oct 9)",
      blockers: [
        "Confirm the second R (Realignment?)",
        "What the $19.99 / $120.99 figure is for",
        "Masterclass price not set",
      ],
      notion: "https://app.notion.com/p/3da98dba651b8140a436ff4f5b2431f3",
      tasks: [
        ["Skool community built, seeded, handed off", true],
        ["Sept 13 launch presentation", true],
        ["Workbook standardized to NKJV + audit", true],
        ["Content batched through Oct 9", true],
        ["Men's fellowship meeting recorded", true],
        ["Strategy call (Sat Sept 12)", true],
        ["Invoice $150 for recording (paid)", true],
        ["Collect $888 unpaid retainer (Aug + Sept)", false, "urgent"],
        ["Rebatch content starting Mon Oct 5", false],
      ],
    },
    {
      id: "landscaping",
      name: "Landscaping Website",
      contact: "HVQ Landscaping (Hector), confirm",
      color: "teal",
      emoji: "🌿",
      type: "project",
      value: 600,
      valueLabel: "$600 · not invoiced",
      status: "waiting",
      services: ["Website build", "Gallery", "4–5 pages", "EN + ES intake"],
      summary: "Website build with gallery and 4–5 pages. Wufoo intake form is ready in EN + ES.",
      next: "Send the Wufoo intake form and follow up until it comes back",
      blockers: ["Waiting on client intake form"],
      notion: "https://app.notion.com/p/2a598dba651b80d580bbe5ddfcd94631",
      tasks: [
        ["Build Wufoo intake form (EN + ES)", true],
        ["Send form to client + follow up", false, "urgent"],
        ["Create $600 invoice in QuickBooks", false],
        ["Build site: gallery + 4–5 pages", false],
      ],
    },
    {
      id: "elevate",
      name: "Elevate BSI (in-house)",
      contact: "Kevin",
      color: "green",
      emoji: "🟢",
      type: "internal",
      value: 0,
      valueLabel: "Own brand",
      status: "active",
      services: ["Social", "Reels", "SEO"],
      summary: "September feed is scheduled. October batch is in progress.",
      next: "Finish October content batch after client items",
      blockers: [],
      notion: "https://app.notion.com/p/39898dba651b812e9e95cee34f181655",
      tasks: [
        ["September feed scheduled", true],
        ["Batch October content", false],
        ["October reels: ElevenLabs VO → Higgsfield B-roll → schedule Thursdays", false],
        ["Upload LLM file into cPanel", false, "blocked"],
        ["Update GMB + Search Console + Bing", false],
      ],
    },
  ],

  prospects: [
    {
      name: "Starlese",
      detail: "Century 21 agent, North Carolina",
      status: "parked",
      note: "Sample package sent, no reply. Text follow-up parked.",
    },
    {
      name: "JPM Solution Corp.",
      detail: "Milton & Alicia Monroy",
      status: "parked",
      note: "Asked for a social media + branding quote (Mar 2026).",
    },
  ],

  // Dated items for the timeline strip
  timeline: [
    { date: "2026-09-14", client: "nyti", label: "NYTI launch + on-site Skool setup", done: true },
    { date: "2026-09-20", client: "relevate", label: "Relevate batch produced", done: true },
    { date: "2026-09-21", client: "nyti", label: "Record NYTI final 4 reels" },
    { date: "2026-10-05", client: "warriors", label: "Warriors next content cycle" },
    { date: "2026-10-09", client: "warriors", label: "Warriors content runs out" },
    { date: "2026-10-19", client: "relevate", label: "Book Relevate Oct 24–31" },
    { date: "2026-10-23", client: "relevate", label: "Relevate schedule ends" },
  ],
};
